### ISSUE TITLE
False answers running HAWK and questions about Fuseki and Indexing

### ISSUE THREAD

**Issue by dobraczka** [dice-group/NLIWOD#31]
Hello, I'm trying to familiarize myself with HAWK and have encountered some problems.
Executing HAWK using `mvn spring-boot:run` worked well, but unfortunately I have yet to get back a correct answer, e.g. the answer for the query `localhost:8181/simple-search?query=What is the capital of Spain ?` was `http://dbpedia.org/resource/Captain_Alatriste` (At least this was found under the `answer` key) which is obviously wrong. I have attached the complete result for reference: [response.txt](https://github.com/AKSW/NLIWOD/files/769574/response.txt) . My question is now: Did I do something wrong or is this a known issue?

After having run `index_fuseki.sh` as suggested in the `qa.hawk/deploy-scripts/README.md` I tried to unzip the file I downloaded from ( http://139.18.2.164/rusbeck/hawk/index_2016-04.zip), which was not possible and returned the following: 
``` Archive:  index_2016-04.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of index_2016-04.zip or
        index_2016-04.zip.zip, and cannot find index_2016-04.zip.ZIP, period.
``` 
I don't think the file got corrupted while I downloaded it, because I downloaded it muliple times. 

Building and running the docker image for the Fuseki server however was successful.
Which brings me to the last question: Does hawk automatically search for this fuseki server on port 3030 or do I have to configure this somewhere?

**Comment by RicardoUsbeck** [comment]
Thanks for trying out HAWK!

HAWK is currently under heavy development which is partly why you cannot get an answer. The second reason is that HAWK is tuned for hybrid queries demanding a text portion to answer it. Simple queries thus are currently not working. A fix is expected soon (until April).

Second, the SPARQL.java class determines the endpoint. 

Third, I will try to reupload the index...But here is an official endpoint in the mean time http://139.18.2.164:3030/

**Comment by dobraczka** [comment]
Thank you!

**Comment by RicardoUsbeck** [comment]
I'll leave it open until we fixed the download issue

**Comment by RicardoUsbeck** [comment]
#34
