### ISSUE TITLE
Unreachable SPARQL endpoint

### ISSUE THREAD

**Issue by NSeydoux** [dice-group/NLIWOD#34]
Hello, 
The SPARQL endpoints required by HAWK (http://139.18.2.164:3030/ds/sparql or http://titan.informatik.uni-leipzig.de:3030/ds/) are not available, and neither is the demo on http://titan.informatik.uni-leipzig.de:8181/. 

Connexion to ws.okbqa.org:7042 is also impossible, preventing maven installation (it is required by the unit tests)

**Comment by RicardoUsbeck** [comment]
Hi there, 

thanks for looking into hawk. We are currently moving our endpoints and thus the store is not available. 

But you can start the store locally https://github.com/AKSW/NLIWOD/tree/master/qa.hawk/deploy-scripts 

You can skip the tests with maven by `mvn clean install -DskipTests`

Are your issues now resolved?
