### ISSUE TITLE
[qa.commons] Standalone Method for syncing the results of QALD

### ISSUE THREAD

**Issue by TortugaAttack** [dice-group/NLIWOD#39]
Instead of having in each QALD loading (for json, xml,...) a method which trys to derive the current results, create one method `syncingResults(List<IQuestion> questions)`.

**Comment by JonathanHuthmann** [comment]
Oops. Referenced wrong issue there! https://github.com/dice-group/NLIWOD/commit/969fd7cc708cd3d70b199b67f5b6662f6e6a94e0 Introduces an AnswerSyncer class, to make this completely independent from classes which handle datasets. Loading and syncing should now look something like this:

`List<IQuestion> questions = LoaderController.load(Dataset);`
`AnswerSyncer.syncAnswers(questions, endpoint, timeoutInSeconds); `

What's left to to is factoring answer syncing out of all other classes.

**Comment by RicardoUsbeck** [comment]
Solved by using https://github.com/dice-group/QUANT to create new datasets
