### ISSUE TITLE
Hardcoding of paths in deploy scripts

### ISSUE THREAD

**Issue by prasanthhs** [dice-group/NLIWOD#41]
Is it possible to change to Environment variables instead of fixed hardcoded absolute path? (z.B /home/datascience/.....).  WE have to manually change path to run scripts in case code is not created in that path.

**Comment by RicardoUsbeck** [comment]
Please point to the files

**Comment by prasanthhs** [comment]
Sorry for the incomplete information.
Files are
fuseki_new.ttl and fuseki_text.ttl.
Fuseki_text.ttl gets called on deployment without docker and returns error due to missing initial path.

**Comment by rrichajalota** [comment]
The path has been changed in both the files, so it should work now. :)

**Comment by RicardoUsbeck** [comment]
please test and close

**Comment by rrichajalota** [comment]
Yeah I tested it. Works for me!

**Comment by RicardoUsbeck** [comment]
@prasanthhs does it also work for you?

That's what I actually meant :)
