### ISSUE TITLE
Hawk does not return answer for Q&A

### ISSUE THREAD

**Issue by prasanthhs** [dice-group/NLIWOD#42]
Answer tag is missing in response.  Reason seems to be issue in Sparql end points.
[log.pdf](https://github.com/dice-group/NLIWOD/files/1487510/log.pdf)

**Comment by rrichajalota** [comment]
Answer is being returned for hybrid queries like: "Which anti-apartheid activist was born in Mvezo?"

**Comment by prasanthhs** [comment]
Seems to be working fine mostly. Closing the issue!
